## VERSION 1 : GETTING STARTED
version: "3"
services:
  web-app:
    stdin_open: true # to prevent bug with the Create React App
    # restart: always
    # build: . will not work for Dockerfile.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - /home/node/app/node_modules #don't map this
      - .:/home/node/app #map all the rest
