apiVersion: v1
kind: Pod
metadata:
  name: sample-k8s-pod
  labels:
    component: web
spec:
  containers:
    - name: nodejs-app
      # image: burakunuvar/dockerized-node-app-image
      image: burakunuvar/dockerized-react-app-image
      ports:
        - containerPort: 3000
